# Generated by Django 4.1.7 on 2023-02-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('mod_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
